UserManagementFA2023/UserManagementFA2023/Controllers/AuthController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using UserManagementFA2023.Models.DTO;
using UserManagementFA2023.Service;
using UserManagementFA2023.Service.IService;
using UserManagementFA2023.Utility;

namespace UserManagementFA2023.Controllers
{
    public class AuthController : Controller
    {

        private readonly IAuthService _authService;
		private readonly ITokenProvider _tokenProvider;
        public AuthController(IAuthService authService, ITokenProvider tokenProvider)
        {
            _authService = authService;
			_tokenProvider = tokenProvider;
        }
		[HttpGet]
        public IActionResult Login(string message)
        {
			LoginRequestDTO loginRequestDTO = new();
			return View(loginRequestDTO);
		}
        [HttpPost]
		public async Task<IActionResult> Login(LoginRequestDTO obj)
		{
			ResponseDTO responseDTO = await _authService.LoginAsync(obj);
			if (responseDTO != null && responseDTO.IsSuccess)
			{
				LoginResponseDTO loginResponseDTO =
					JsonConvert.DeserializeObject<LoginResponseDTO>(Convert.ToString(responseDTO.Result));

				await SignInuser(loginResponseDTO);
				_tokenProvider.SetToken(loginResponseDTO.Token);
				return RedirectToAction("Index", "Home");
			}
			else
			{
				ModelState.AddModelError("CustomError", responseDTO.Message);
				return View(obj);
			}
		}
		[HttpGet]
		public IActionResult Register(string message)
		{
			ViewData["message"] = message;
			return View();
		}
		[HttpPost]
		public async Task<IActionResult> Register(RegisterationRequestDTO obj)
		{
			ResponseDTO result = await _authService.RegisterAsync(obj);
			ResponseDTO assignRole;
			if (result != null && result.IsSuccess)
			{
				obj.Role = SD.RoleTrainer;
				assignRole = await _authService.AssignRoleAsync(obj);
				if (assignRole != null && assignRole.IsSuccess)
				{
					TempData["success"] = "Registration Successful";
					return RedirectToAction(nameof(Login));
				}
			}
			else
			{
				TempData["error"] = result.Message;
			}
			return View(obj);
		}
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            _tokenProvider.ClearToken();
            return RedirectToAction("Index", "Home");
        }
        private async Task SignInuser(LoginResponseDTO model)
		{
			var handler = new JwtSecurityTokenHandler();
			var jwt = handler.ReadJwtToken(model.Token);
			var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
			identity.AddClaim(new Claim(JwtRegisteredClaimNames.Email, jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Email).Value));
			identity.AddClaim(new Claim(JwtRegisteredClaimNames.Sub, jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Sub).Value));
			identity.AddClaim(new Claim(JwtRegisteredClaimNames.Name, jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Name).Value));
			identity.AddClaim(new Claim(ClaimTypes.Name, jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Email).Value));

			var principal = new ClaimsPrincipal(identity);
			await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
		}
	}
}

UserManagementFA2023/UserManagementFA2023/Controllers/ClassController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using Newtonsoft.Json;
using UserManagementFA2023.Models.DTO;
using UserManagementFA2023.Service;
using UserManagementFA2023.Service.IService;

namespace UserManagementFA2023.Controllers
{
	public class ClassController : Controller
	{
		private readonly IClassService _classService;
		private readonly ILocationService _locationService;
		private	readonly ILevelService _levelService;
        private readonly IUserService _userService;
        public ClassController(IClassService classService,ILocationService locationService,ILevelService levelService, IUserService userService)
		{
			_classService = classService;
			_locationService = locationService;
			_levelService = levelService;
			_userService = userService;
		}

		public async Task<IActionResult> ClassIndex(int page = 1 , int pageSize = 3)
		{
            List<ClassDTO>? listClass ;
			List<LocationDTO>? listLocation;
			List<LevelDTO>? listLevel;
			List<UserDTO>? listUser;
			PageDTO? pageDTO = new PageDTO();
			ResponseDTO? responseClass = await _classService.GetClass(page, pageSize);
			ResponseDTO? responseLocation = await _locationService.GetAllLocation();
			ResponseDTO? responseLevel = await _levelService.GetAllLevel();
            ResponseDTO? responseUser = await _userService.GetAllUser();
            ClassListViewDTO classListViewDTO = new ClassListViewDTO();


            if (responseClass != null && responseClass.IsSuccess && responseLocation != null && responseLocation.IsSuccess
                && responseLevel != null && responseLevel.IsSuccess && responseUser != null && responseUser.IsSuccess)
			{
                listClass = JsonConvert.DeserializeObject<List<ClassDTO>>(Convert.ToString(responseClass.Result));
                listLocation = JsonConvert.DeserializeObject<List<LocationDTO>>(Convert.ToString(responseLocation.Result));
				listLevel = JsonConvert.DeserializeObject<List<LevelDTO>>(Convert.ToString(responseLevel.Result));
				listUser = JsonConvert.DeserializeObject<List<UserDTO>>(Convert.ToString(responseUser.Result));
				var stringPage = Convert.ToString(responseClass.Message);
                string[] parts = stringPage.Split(':');
                if (parts.Length == 2)
                {
                    string totalPageString = parts[1].Trim(); 
					
                    if (int.TryParse(totalPageString, out int totalPage))
                    {
                        pageDTO.TotalPage = totalPage;
						pageDTO.CurrentPageNumber = page;
						pageDTO.PageSize = pageSize;
					}
				}
                if (!listClass.IsNullOrEmpty() && !listLocation.IsNullOrEmpty() &&
					!listLevel.IsNullOrEmpty() && !listUser.IsNullOrEmpty()
					)  
				{
					classListViewDTO.classDTOs = listClass;
                    classListViewDTO.locationDTOs = listLocation;
					classListViewDTO.levelDTOs = listLevel;
					classListViewDTO.userDTOs = listUser;
					classListViewDTO.pageDTO = pageDTO;
                }
				
            }
			else
			{
				/*TempData["error"] = response?.Message;*/
			}

			

			return View(classListViewDTO);
		}
        public async Task<IActionResult> CreateClassDetails()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateClassDetails(ClassDetailsDTO c)
        {
            if (ModelState.IsValid)
            {
                ResponseDTO? response = await _classService.CreateClass(c);

                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Syllabus created successfully";
                    return RedirectToAction(nameof(CreateClassDetails));
                }
                else
                {
                    TempData["error"] = response?.Message;
                }
            }
            return View();
        }
    }
}

UserManagementFA2023/UserManagementFA2023/Controllers/SyllabusController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using Newtonsoft.Json;
using UserManagementFA2023.Models.DTO;
using UserManagementFA2023.Service;
using UserManagementFA2023.Service.IService;

namespace UserManagementFA2023.Controllers
{
    public class SyllabusController : Controller
    {
        private readonly ISyllabusService _syllabusService;
        private readonly IStatusService _statusService;
        public SyllabusController(ISyllabusService syllabusService, IStatusService statusService)
        {
            _syllabusService = syllabusService;
            _statusService = statusService;
        }

        public async Task<IActionResult> SyllabusIndex()
        {
            List<SyllabusDTO> listSyllabus;
            List<StatusDTO> listStatus;

            ResponseDTO? responseSyllabus = await _syllabusService.GetAllSyllabus();
            ResponseDTO? responseStatus = await _statusService.GetAllStatus();

            CombinedSyllabusModelDTO syllabusListViewDTO = new CombinedSyllabusModelDTO();

            if (responseSyllabus != null && responseSyllabus.IsSuccess && responseStatus != null && responseStatus.IsSuccess)
            {
                listSyllabus = JsonConvert.DeserializeObject<List<SyllabusDTO>>(Convert.ToString(responseSyllabus.Result));
                listStatus = JsonConvert.DeserializeObject<List<StatusDTO>>(Convert.ToString(responseStatus.Result));
                if (!listSyllabus.IsNullOrEmpty() && !listStatus.IsNullOrEmpty())
                {
                    syllabusListViewDTO.syllabusDTOs = listSyllabus;
                    syllabusListViewDTO.statusDTOs = listStatus;
                }
                else
                {
                    TempData["error"] = responseSyllabus?.Message;
                }

            }
            return View(syllabusListViewDTO);
        }
        [HttpGet]
        public async Task<IActionResult> CreateSyllabusDetails()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateSyllabusDetails(SyllabusDetailsDTO sy)
        {
            if (ModelState.IsValid)
            {
                ResponseDTO? response = await _syllabusService.CreateSyllabus(sy);

                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Syllabus created successfully";
                    return RedirectToAction(nameof(CreateSyllabusDetails));
                }
                else
                {
                    TempData["error"] = response?.Message;
                }
            }
            return View();
        }
        public async Task<IActionResult> SyllabusDetail(int syllabusId)
        {
            SyllabusDetailsDTO syllabusDetail = new SyllabusDetailsDTO();
            try
            {
                ResponseDTO? response = await _syllabusService.GetSyllabusDetail(syllabusId);
                if (response != null && response.IsSuccess)
                {
                    syllabusDetail = JsonConvert.DeserializeObject<SyllabusDetailsDTO>(Convert.ToString(response.Result));
                }
                else
                {
                    TempData["error"] = response?.Message;
                }
            }
            catch (Exception ex)
            {
                TempData["error"] = "Đã xảy ra lỗi: " + ex.Message;
                Console.WriteLine("Lỗi: " + ex.ToString());
            }

            return View(syllabusDetail);
        }
    }
}

UserManagementFA2023/UserManagementFA2023/Controllers/TrainingController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using Newtonsoft.Json;
using UserManagementFA2023.Models.DTO;
using UserManagementFA2023.Service;
using UserManagementFA2023.Service.IService;

namespace UserManagementFA2023.Controllers
{
    public class TrainingController : Controller
    {
        private readonly ITrainingService _trainingService;

        public TrainingController(ITrainingService trainingService)
        {
            _trainingService = trainingService;
        }
        public async Task<IActionResult> TrainingIndex()
        {
            List<TrainingProgramDTO> trainingProgram = new List<TrainingProgramDTO>();
            try
            {
                ResponseDTO? response = await _trainingService.GetAllTrainingProgram();
                if (response != null && response.IsSuccess)
                {
                    trainingProgram = JsonConvert.DeserializeObject<List<TrainingProgramDTO>>(Convert.ToString(response.Result));
                }
                else
                {
                    TempData["error"] = response?.Message;
                }
            }
            catch (Exception ex)
            {
                TempData["error"] = "Đã xảy ra lỗi: " + ex.Message;
                Console.WriteLine("Lỗi: " + ex.ToString());
            }

            return View(trainingProgram);
        }


    }
}

UserManagementFA2023/UserManagementFA2023/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UserManagementFA2023</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UserManagementFA2023.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link href="~/css/sidenav.css" rel='stylesheet'>
</head>
<style>
    .navbar-nav .nav-item a.nav-link {
        color: #90ffb8;
    }

    .navbar-nav .nav-item a.nav-link:hover {
        color: #FAFAFA; 
    }
</style>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  box-shadow" style="background-color:rgba(45, 55, 72, 1);margin: 0px;">
            <div class="container-fluid" id="mainnav" style=" transition: 0.6s;">

                <span id="menu-icon" style="font-size:30px;cursor:pointer;color:white; margin-right: 20px;" onclick="openNav()">&#9776;</span>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/fptlogo.png" />
                </a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Syllabus" asp-action="SyllabusIndex">Syllabus</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Syllabus" asp-action="CreateSyllabusDetails">CreateSyllabus</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Class" asp-action="ClassIndex">Class</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Training" asp-action="TrainingIndex">TrainingProgram</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>

                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="#">Hello, @User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Auth" asp-action="Logout">Log out</a>
                            </li>
                        }
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="" style="margin: 0 0;">
        <div id="mySidenav" class="sidenav">
            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
            @*             <a href="#">About</a>
            <a href="#">Services</a>
            <a href="#">Clients</a>
            <a href="#">Contact</a> *@
        </div>
        <main role="main" class="" id="main">
            @RenderBody()
        </main>

    </div>

    @* <footer class="border-top footer text-muted">
    <div class="container">
    &copy; 2023 - UserManagementFA2023 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://unpkg.com/ionicons@5.1.2/dist/ionicons.js"></script>
    <script src="~/js/sidenav.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>